class_name FlatColorWorldBuilder # Reuses the existing procedural map layout while rendering it with simple debug colors only.
extends HgssWorldBuilder # Keeps terrain layout, elevation, collision, entry points, and navigation queries unchanged.

const GRASS_COLOR: Color = Color(0.34, 0.62, 0.36, 1.0) # Marks ordinary walkable grass.
const PATH_COLOR: Color = Color(0.76, 0.66, 0.43, 1.0) # Marks the connected dirt-route network.
const TALL_GRASS_COLOR: Color = Color(0.19, 0.46, 0.24, 1.0) # Marks encounter-field terrain.
const WATER_COLOR: Color = Color(0.22, 0.50, 0.76, 1.0) # Marks non-walkable rivers, ponds, and lakes.
const STONE_COLOR: Color = Color(0.50, 0.52, 0.50, 1.0) # Marks raised plazas and rocky terrain.
const FOREST_COLOR: Color = Color(0.12, 0.31, 0.16, 1.0) # Marks tree-blocker cells with a single simple object color.

func _ready() -> void: # Builds the same procedural world without loading any external world art assets.
    add_to_group(&"world_builder") # Preserves the semantic lookup used by navigation and roaming Pokémon.
    _prepare_layout_cache() # Reuses the existing deterministic terrain and blocker layout.
    _build_terrain_geometry() # Reuses the existing height field and collision generation with overridden flat materials.
    _build_forest_visuals() # Replaces decorative tree geometry with simple flat-color blocker boxes.
    _prepare_entry_points() # Preserves all existing roaming Pokémon entrances and exits.

func _create_terrain_materials() -> Dictionary: # Defines one untextured material for each terrain classification.
    var materials: Dictionary = {} # Stores materials by the inherited TerrainKind enum value.
    materials[TerrainKind.GRASS] = _create_flat_material(GRASS_COLOR) # Uses one solid green for ordinary grass.
    materials[TerrainKind.PATH] = _create_flat_material(PATH_COLOR) # Uses one solid tan for paths and bridges.
    materials[TerrainKind.TALL_GRASS] = _create_flat_material(TALL_GRASS_COLOR) # Uses a darker green for encounter fields.
    materials[TerrainKind.WATER] = _create_flat_material(WATER_COLOR) # Uses one blue for all water surfaces.
    materials[TerrainKind.STONE] = _create_flat_material(STONE_COLOR) # Uses one neutral gray for stone and raised plaza surfaces.
    return materials # Returns a complete material set with no texture or model dependencies.

func _build_forest_visuals() -> void: # Represents every tree blocker as a simple colored box while preserving exact blocker positions.
    var tree_cells: Array[Vector2i] = [] # Collects the same blocked cells generated by the inherited layout rules.
    for key: Variant in blocked_cells.keys(): # Traverses every hard forest cell in the procedural map.
        tree_cells.append(Vector2i(key)) # Converts the dictionary key back to its grid coordinate without resource dependencies.
    if tree_cells.is_empty(): # Guards a future layout variant with no forest blockers.
        return # Avoids allocating an empty MultiMesh.
    var forest_material: StandardMaterial3D = _create_flat_material(FOREST_COLOR) # Uses one solid color for all temporary forest objects.
    var forest_mesh: BoxMesh = BoxMesh.new() # Uses a built-in primitive instead of any imported model.
    forest_mesh.size = Vector3(TILE_SIZE * 0.72, TREE_BLOCKER_HEIGHT, TILE_SIZE * 0.72) # Keeps the marker inside its blocked cell while remaining clearly visible.
    forest_mesh.material = forest_material # Shares one material across every forest marker instance.
    _create_tree_multimesh("forest_blocks", forest_mesh, tree_cells, TREE_BLOCKER_HEIGHT * 0.5) # Batches all object markers into one draw-efficient MultiMesh.

func _create_flat_material(color: Color) -> StandardMaterial3D: # Creates a deliberately plain material suitable for layout-first development.
    var material: StandardMaterial3D = StandardMaterial3D.new() # Uses Godot's built-in material with no texture inputs.
    material.albedo_color = color # Represents the entire surface with one semantic color.
    material.shading_mode = BaseMaterial3D.SHADING_MODE_UNSHADED # Keeps colors visually constant and removes lighting/material complexity.
    material.cull_mode = BaseMaterial3D.CULL_DISABLED # Keeps the existing procedural terrain visible regardless of triangle-facing direction.
    return material # Returns an opaque, texture-free material.
