class_name PokemonSpriteLibrary # Provides runtime discovery and cached SpriteFrames creation for downloaded HGSS Pokémon sprites.
extends RefCounted # Keeps the asset utility lightweight because it does not need to exist in the scene tree.

const DEFAULT_ROOT: String = "res://assets/pokemon/hgss_overworld" # Defines the project folder containing numbered Pokémon sprite directories.
const DIRECTIONS: Array[StringName] = [&"down", &"up", &"left", &"right"] # Defines the directional animation names expected from the downloader.

static var _sprite_frames_cache: Dictionary[String, SpriteFrames] = {} # Reuses constructed animation resources so repeated species do not reload every texture.
static var _form_cache: Dictionary[String, PackedStringArray] = {} # Reuses valid form-directory lookups for each discovered species.

static func discover_species(root_path: String = DEFAULT_ROOT) -> PackedStringArray: # Finds Pokémon number folders containing at least one complete normal overworld sprite set.
    var species_directories: PackedStringArray = PackedStringArray() # Stores valid species folders as project resource paths.
    for entry: String in ResourceLoader.list_directory(root_path): # Reads project resources in a way that remains usable after export.
        if not entry.ends_with("/"): # Ignores files because the root should contain numbered directories only.
            continue # Skips non-directory resources without doing further validation.
        var directory_name: String = entry.trim_suffix("/") # Removes ResourceLoader's directory marker before validating the Pokédex identifier.
        if not directory_name.is_valid_int(): # Rejects unrelated folders that are not numeric Pokédex identifiers.
            continue # Keeps discovery restricted to the downloader's expected directory structure.
        var species_directory: String = root_path.path_join(directory_name) # Builds the full resource path for the candidate Pokémon.
        if get_form_directories(species_directory).is_empty(): # Rejects species that do not contain a complete usable normal form.
            continue # Prevents the spawner from selecting incomplete assets.
        species_directories.append(species_directory) # Records the valid species for uniform random selection later.
    species_directories.sort() # Makes discovery deterministic before random selection is applied deliberately.
    return species_directories # Returns every usable species currently present in the project asset folder.

static func get_form_directories(species_directory: String) -> PackedStringArray: # Finds complete normal sprite directories for every form of one species.
    if _form_cache.has(species_directory): # Checks whether this species has already been scanned during the current run.
        return _form_cache[species_directory] # Reuses the previous result instead of repeatedly traversing the resource directory.
    var form_directories: PackedStringArray = PackedStringArray() # Stores complete normal sprite paths for the species' available forms.
    for entry: String in ResourceLoader.list_directory(species_directory): # Reads every form directory generated by the downloader.
        if not entry.ends_with("/"): # Ignores unexpected files at the species-directory level.
            continue # Continues scanning only subdirectories that can represent forms.
        var form_name: String = entry.trim_suffix("/") # Removes the directory marker before composing the normal-variant path.
        var normal_directory: String = species_directory.path_join(form_name).path_join("normal") # Selects the standard-colour visual variant for wild spawning.
        if not _has_complete_direction_set(normal_directory): # Validates all four directions and both animation frames before accepting a form.
            continue # Excludes incomplete form assets that would cause missing animation frames at runtime.
        form_directories.append(normal_directory) # Records the complete form's normal sprite directory.
    form_directories.sort() # Keeps form discovery deterministic before the explicit random form choice.
    _form_cache[species_directory] = form_directories # Caches the validated form list for future spawns of this species.
    return form_directories # Returns every complete normal form available for the chosen species.

static func choose_random_sprite_directory(species_directories: PackedStringArray, random: RandomNumberGenerator) -> String: # Chooses a species uniformly, then chooses one of that species' forms uniformly.
    if species_directories.is_empty(): # Guards projects where the Pokémon sprite folder is missing or empty.
        return "" # Reports that no valid sprite set can be selected.
    var species_index: int = random.randi_range(0, species_directories.size() - 1) # Selects one Pokédex species without overweighting species that have many forms.
    var species_directory: String = species_directories[species_index] # Reads the selected numbered species resource path.
    var form_directories: PackedStringArray = get_form_directories(species_directory) # Gets the validated forms available for that species.
    if form_directories.is_empty(): # Guards against assets changing after the initial discovery scan.
        return "" # Rejects the selection if no valid form remains available.
    var form_index: int = random.randi_range(0, form_directories.size() - 1) # Selects one form of the chosen species uniformly.
    return form_directories[form_index] # Returns the directory containing the eight directional PNG resources.

static func get_sprite_frames(sprite_directory: String) -> SpriteFrames: # Builds or retrieves the directional animation library for one Pokémon form.
    if _sprite_frames_cache.has(sprite_directory): # Checks whether this exact form has already been prepared.
        return _sprite_frames_cache[sprite_directory] # Reuses the cached SpriteFrames and the textures already cached by ResourceLoader.
    var sprite_frames: SpriteFrames = SpriteFrames.new() # Creates a runtime animation resource for this Pokémon form.
    if sprite_frames.has_animation(&"default"): # Checks for the automatically created default animation.
        sprite_frames.remove_animation(&"default") # Removes the unused default so the resource contains only meaningful directional animations.
    for direction: StringName in DIRECTIONS: # Creates matching idle and walking animations for all four HGSS directions.
        var idle_animation: StringName = StringName("idle_" + String(direction)) # Builds the idle animation identifier expected by BillboardCharacterVisual.
        var walk_animation: StringName = StringName("walk_" + String(direction)) # Builds the walking animation identifier expected by BillboardCharacterVisual.
        var frame_zero_path: String = sprite_directory.path_join(String(direction) + "_0.png") # Builds the first source-frame resource path for this direction.
        var frame_one_path: String = sprite_directory.path_join(String(direction) + "_1.png") # Builds the second source-frame resource path for this direction.
        var frame_zero: Texture2D = ResourceLoader.load(frame_zero_path, "Texture2D") as Texture2D # Loads the first directional texture through Godot's resource cache.
        var frame_one: Texture2D = ResourceLoader.load(frame_one_path, "Texture2D") as Texture2D # Loads the second directional texture through Godot's resource cache.
        if frame_zero == null or frame_one == null: # Guards against externally modified or partially imported sprite folders.
            push_error("Could not load complete HGSS sprite set from: " + sprite_directory) # Reports the exact asset directory that failed to load.
            return SpriteFrames.new() # Returns an empty resource rather than leaving a partially built animation library cached.
        sprite_frames.add_animation(idle_animation) # Creates the one-frame idle animation for this direction.
        sprite_frames.set_animation_loop(idle_animation, true) # Keeps the idle animation valid for continuous playback.
        sprite_frames.set_animation_speed(idle_animation, 4.0) # Sets a harmless playback rate even though the idle animation contains one frame.
        sprite_frames.add_frame(idle_animation, frame_zero) # Uses the first walking frame as the matching stationary pose.
        sprite_frames.add_animation(walk_animation) # Creates the two-frame HGSS walking animation for this direction.
        sprite_frames.set_animation_loop(walk_animation, true) # Loops walking continuously while the Pokémon is moving.
        sprite_frames.set_animation_speed(walk_animation, 6.0) # Matches the existing Ditto walk cadence used by the starter project.
        sprite_frames.add_frame(walk_animation, frame_zero) # Adds the first HGSS walking pose to the animation.
        sprite_frames.add_frame(walk_animation, frame_one) # Adds the second HGSS walking pose to the animation.
    _sprite_frames_cache[sprite_directory] = sprite_frames # Caches the complete runtime resource for future instances of this form.
    return sprite_frames # Returns the ready-to-use directional animation library.

static func _has_complete_direction_set(sprite_directory: String) -> bool: # Checks that a candidate folder has both frames for all four required directions.
    for direction: StringName in DIRECTIONS: # Validates every cardinal direction used by the billboard visual controller.
        var frame_zero_path: String = sprite_directory.path_join(String(direction) + "_0.png") # Builds the first expected PNG resource path.
        var frame_one_path: String = sprite_directory.path_join(String(direction) + "_1.png") # Builds the second expected PNG resource path.
        if not ResourceLoader.exists(frame_zero_path, "Texture2D"): # Checks whether Godot recognizes the first imported direction frame.
            return false # Rejects the candidate immediately when a required frame is absent.
        if not ResourceLoader.exists(frame_one_path, "Texture2D"): # Checks whether Godot recognizes the second imported direction frame.
            return false # Rejects the candidate immediately when a required frame is absent.
    return true # Accepts the sprite directory only when all eight required resources exist.
